### ISSUE TITLE
0MB in activity bar

### ISSUE THREAD

**Issue by jayalberts** [Hivemapper/Community#104]
Some contributors are reporting 3 green lights and 0MB in activities. Some users are seeing their storage increase but the number is not.

**Comment by jayalberts** [comment]
I was able to repro this bug and currently collecting data points from other contributors as team is researching

**Comment by jayalberts** [comment]
We are seeing better stability in our tests for app version 5.0.0 with firmware version 0.13.1. 

Improved accounting for activities and enriched instrumentation so we can find bugs faster in the future.

**Comment by jayalberts** [comment]
If you are experiencing this issue, please check whether or not you have cell uploads on. If you do, you might just be uploading data faster than you are downloading it from the camera.

We are still investigating all the reasons some users are experiencing this issue.

**Comment by jayalberts** [comment]
More instrumentation included in 5.0.4 release.

**Comment by ddemaio** [comment]
I had one instance the other day, where the upload button wasn't on, but it was still uploading. It was rather strange and I hadn't experienced it since. His turned up after the firmware and app update. It is stuck on 0MB for a bit (5 minutes) before the data starts accumulating with the upload button turned off. The app is also giving a "CONNECT DASHCAM WIFI" error even though it is connected to the local dashcam network. When this error happens, the accumulation of data tends to stop (timeout), which sounds like it is associated with #129 & #103

**Comment by nickpoorman** [comment]
I'm on v5.0.4. I think there may be another underlying bug. 

I first too thought maybe it was uploading very fast. But I was driving through a national park yesterday deep in a canyon where there was no chance of any cell service. I have 3x cell networks for the van (I'm doing Van Life). To confirm I looked at my Grafana dashboards, I had zero cellular coverage the whole time.

I racked up well over 1 gig of imagery and then all of a sudden it dropped to zero. Maybe I don't understand the metric above the map... I was under the impression that was the amount of data that still needed to be uploaded?

**Comment by jayalberts** [comment]
@ddemaio 

- if you were on a known wifi network (e.g. home or work wifi) then it makes sense that uploads would be working without the cell uploads enabled. 
- It takes 2-3 minutes for the camera to boot up and 2-3 minutes to begin collecting images, so it is normal that you would see 0MB for ~5 minutes until data starts accumulating.
- If you are getting the CONNECET DASHCAM WIFI notification then you almost certainly lost wifi connection to the camera and the data will stop accumulating. I would expect the dashcam to automatically reconnect itself within 1-2 minutes and resume mapping again. If that doesn't happen then you may need to tap through your settings to manually reconnect to camera wifi. We're working on improving these notifications in next week's update.

**Comment by jayalberts** [comment]
@nickpoorman I'm jealous about the national parks! You are correct about the metric. I can think of a few potential explanations:
- If you were in driving deep between canyons then you may not have had strong GPS lock (even if light was green) and it could have rendered the data unusable. We've been thinking about how to change the LED lights to reflect when GPS might be weaker. If this is the case there is not much you can do.
- Could just be a UI glitch. Leave the app in foreground for a while and see if the data comes back.
- Unknown issue: we can take a look at your logs to see if anything unusual happened on your drive. Please DM me your Hivemapper user name on Discord and the approximate date/time of the drive.

**Comment by jayalberts** [comment]
Over the last couple days we discovered a firmware bug which causes an issue with timestamps. Mismatching timestamps can be causing some of the 0MB issues. We have a fix for this and it will be coming up in the firmware release on track for next week.

**Comment by ddemaio** [comment]
> 

@jayalberts The issues with the connections were fixed in the last update. 

With the mobile upload via cell network, It was super odd. I was in the middle of no where and not connected to any wifi or other network. Setting for data were turned off with the app and also in the mobile os for data sharing. Maybe it automatically connected to a network I had used before within the space of 400 meters, but I was at least 5km from a city, so I find that doubtful. It was a one off thing that happened and I was super surprised by it because it didn't make sense when I looked at all the settings. Just wanted to share for awareness in case you ever see it again.

**Comment by jayalberts** [comment]
@ddemaio very strange indeed. Thank you for sharing! We'll keep an eye out for similar issues.

**Comment by jayalberts** [comment]
It appears with latest updates (app 5.1.6 & 5.2.6 + firmware 0.13.1 & 1.2.3) majority of contributors are experiencing very stable mapping experience and are able to reliably collect images. We have future improvements in the backlog that should continue to improve the percentage of data contributors are collecting and uploading. We're going to close this issue out now and open new tickets for any subsequent issues that become known.
