### ISSUE TITLE
Fix for firmware updates failing

### ISSUE THREAD

**Issue by jayalberts** [Hivemapper/Community#129]
Firmware updates are failing for many users. Currently investigating.

**Comment by jayalberts** [comment]
Found a fix - will be released in 5.1

**Comment by ddemaio** [comment]
I also believe the firmware update had some issues. Its performance dramatically changed and I'm having difficulty with the images loading through the app. There are connection issues and it seems like their could be a driver issue since the upload/connection issue is timing out after 10 to 20 minutes of operating. I've only been able to get max 650mb of image transfer to the app after the firmware update. Not sure what OS you're using in the background. I'm thinking either Ubuntu or some Yocto setup. Might be good to explore MicroOS for next gen devices - https://get.opensuse.org/microos/ O2 had a really bad firmware update that brought down their network. You can hear about there in this talk https://youtu.be/HfaXrp4w648 Having some atomic setup is ideal for the hivemapper firmware setups. The device will need some sort of rollback option as there is a chance one of the firmware updates can break everyone's mapper/IoT device.
